version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=dev_secret_key
      - GCP_PROJECT_ID=simple-manip-survey-250416
      - GOOGLE_APPLICATION_CREDENTIALS=/app/iac/service-account-key.json
      - FIRESTORE_EMULATOR_HOST=firestore-emulator:8080
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - firestore-emulator

  firestore-emulator:
    image: mtlynch/firestore-emulator:latest
    ports:
      - "8080:8080"
    environment:
      - FIRESTORE_PROJECT_ID=simple-manip-survey-250416
      - PORT=8080
    volumes:
      - firestore-data:/data

volumes:
  firestore-data:
